core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from dashboard.dashboard_views import sos, emergencia, fuego, success

urlpatterns = [
    
    
    ## envios de alertas desde el dispositivo del usuario a través de google home y estos links:
    path('s/', sos, name="sos"), 
    path('e/', emergencia, name="emergencia"), 
    path('f/', fuego, name="fuego"),  
    
    path('alerta-enviada/<uuid:pk>/', success, name="success"),  

    path('',  include('dashboard.urls', namespace='dashboard')),   




    path('admin/', admin.site.urls),
   
    #Dashboard
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    #Frontend
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/cms/blog/urls.py
from django.urls import path 
from dashboard.cms.blog.views import (
                                        cms_blog_list,
                                        cms_blog_delete,
                                        cms_blog_create,
                                        cms_blog_add_category,
                                        cms_blog_edit,
                                        # cms_blog_custom_field_delete,
                                        delete_multiple_blogs,
                                        blogCategory,
                                        blogCategoryDelete,
                                        blogCategoryEdit,
                                        blogTag,
                                        blogTagEdit,
                                        blogTagDelete,
                                      
                                       
                                    )


app_name='blog'
urlpatterns = [
    path('', cms_blog_list, name='blogs'),
    path('create/',cms_blog_create, name='blog_create'),
    path('edit/<int:id>',cms_blog_edit, name='blog_edit'),
    path('blog_delete/<int:id>/',cms_blog_delete, name='blog_delete'),
    path('blog_category_add/',cms_blog_add_category, name='blog_category_add'),
    # path('blog_custom_field_delete/<int:id>/',cms_blog_custom_field_delete, name="blog_custom_field_delete"),
    path('delete-multiple-blogs/',delete_multiple_blogs, name='delete-multiple-blogs'),
    
    path('categories/',blogCategory, name='blogCategory'),
    path('category-delete/<int:id>/',blogCategoryDelete, name='blogCategoryDelete'),
    path('category-edit/<int:id>/',blogCategoryEdit, name='blogCategoryEdit'),
    
    path('tags/',blogTag, name='blogTag'),
    path('tag-edit/<int:id>/',blogTagEdit, name='blogTagEdit'),
    path('tag-delete/<int:id>/',blogTagDelete, name='blogTagDelete'),

    

   
]

dashboard/cms/menu/urls.py
from django.urls import path 
from dashboard.cms.menu.views import (

    cms_menu_setup,
    cms_menu_item_delete,
    cms_menu_structure_save,
    cms_menu_create,
    cms_menu_delete,
    cms_search_menu,
    add_menu_content,
    add_link_to_menu

)

app_name='menu'
urlpatterns = [
    path('setup/', cms_menu_setup, name='setup'),
    path('setup/<int:id>/', cms_menu_setup, name='setup'),
    path('menu_item_delete/', cms_menu_item_delete, name='menu_item_delete'),
    path('menu_structure_save/', cms_menu_structure_save, name='menu_structure_save'),
    path('create_menu/', cms_menu_create, name='create_menu'),
   
    path('menu_delete/', cms_menu_delete, name='menu_delete'),
    path('search_menu/', cms_search_menu, name='search_menu'),
    
    path('add_content_to_menu/',add_menu_content, name='add_content_to_menu'),
    path('add_link_to_menu/',add_link_to_menu, name='add_link_to_menu'),

]

dashboard/urls.py
from dashboard.users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path ,include
from dashboard import dashboard_views
from dashboard.users import users_views
app_name='dashboard'
urlpatterns = [

#########################################################################    
################  PLANB 

    path('',dashboard_views.index,name="index"),
    path('index/',dashboard_views.index,name="index"),
    
    
    ###  USERS module

    path('usuarios/',dashboard_views.users_list,name="usuarios"),
    path('usuario/add/',dashboard_views.useradd,name="useradd"),    
    path('usuario/<uuid:pk>/',dashboard_views.usuario_detail, name="usuario"),
    path('usuario/<uuid:pk>/delete/',dashboard_views.usuario_delete, name="usuariodelete"),
    
  ###  ALARMS ALERTS module
    path('alarmas/user/<uuid:pk>', dashboard_views.alertas, name="usuarioalertas"),

    
    path('alarmas/', dashboard_views.alertas, name="alertas"),
    
    # ajax monitoreo de alarmas
    path('alarmas/latest/', dashboard_views.latest, name='latest'),
    path('alarmas/has_new_data/', dashboard_views.has_new_data, name='has_new_data'),
    path('api/alarms/', dashboard_views.AlarmaEventAPIView.as_view(), name='apialarm'),



  ###  BARRIOS VIVIENDA  module

    path('barrios/',dashboard_views.barrios_list, name="barrios"),
    path('barrio/add/',dashboard_views.barrioadd,name="barrioadd"),    

    path('barrio/<uuid:pk>/delete/',dashboard_views.barrio_delete, name="barriodelete"),
    path('barrio/<uuid:pk>/',dashboard_views.barrio_detail, name="barrio"),
    path('barrio/<uuid:pk>/change/',dashboard_views.barrio_edit, name="barrioedit"),
    path('usuarios/<uuid:pk>/',dashboard_views.users_list,name="usuariosbarrio"),

    path('vivienda/<uuid:pk>/delete/',dashboard_views.vivienda_delete, name="viviendadelete"),
    path('vivienda/<uuid:pk>/',dashboard_views.vivienda_detail, name="vivienda"),
    path('vivienda/<uuid:pk>/change/',dashboard_views.vivienda_edit, name="viviendaedit"),
    path('vivienda/add/',dashboard_views.viviendaadd,name="viviendaadd"),    
    

################   end PLANB += index


#########################################################################3    
    
    
    
	path('users/',users_views.users,name="users"),
	path('user-details/<int:id>/',users_views.user_details,name="user-details"),
	path('add-user/',users_views.add_user,name="add-user"),
	path('edit-user/<int:id>/',users_views.edit_user,name="edit-user"),
	path('delete-user/<int:id>/',users_views.delete_user,name="delete-user"),
	path('delete-multiple-user/',users_views.delete_multiple_user,name="delete-multiple-user"),

	path('login/',users_views.login_user,name="login"),
	path('logout/',users_views.logout_user,name="logout"),
	path('groups/',users_views.groups_list,name="groups"),
	path('group-edit/<int:id>/',users_views.group_edit,name="group-edit"),
	path('group-delete/<int:id>/',users_views.group_delete,name="group-delete"),
	path('group-add/',users_views.group_add,name="group-add"),
	path('permissions/',users_views.permissions,name="permissions"),
	path('edit-permissions/<int:id>/',users_views.edit_permissions,name="edit-permissions"),
	path('delete-permissions/<int:id>/',users_views.delete_permissions,name="delete-permissions"),
	path('assign-permissions-to-user/<int:id>/',users_views.assign_permissions_to_user,name="assign-permissions-to-user"),
	path('signup/',users_views.signup,name="signup"),
	path('activate/<uidb64>/<token>/',users_views.activate, name='activate'),


    #CMS_Start-------------------

    path('pages/', include('dashboard.cms.pages.urls', namespace='pages')),
    path('blogs/', include('dashboard.cms.blog.urls', namespace='blog')),
    path('menus/', include('dashboard.cms.menu.urls', namespace='menu')),
    path('subscribe/', include('dashboard.cms.subscribe.urls', namespace='subscribe')),
    path('contact-us/', include('dashboard.cms.contactus.urls', namespace='contactus')),


    path('configurations/',dashboard_views.all_config,name='all-config'),
    path('configurations/reset/',dashboard_views.reset_config,name='reset-config'),
    path('configurations/download/',dashboard_views.download_config,name='download-config'),

    
    path('configurations/prefix/<str:prefix>/',dashboard_views.filter_config,name='filter-config'),
    path('add-configurations/',dashboard_views.add_config,name='add-config'),
    path('edit-configurations/<int:id>/',dashboard_views.edit_config,name='edit-config'),
    path('delete-configurations/<int:id>/',dashboard_views.delete_config,name='delete-config'),
    #CMS_End-----------------
    path('',dashboard_views.index,name="index"),
    path('index/',dashboard_views.index,name="index"),
    path('activity/',dashboard_views.activity,name="activity"),
    path('profile/',dashboard_views.profile,name="profile"),
    path('page-lock-screen/',dashboard_views.page_lock_screen,name="page-lock-screen"),
    path('page-error-400/',dashboard_views.page_error_400,name="page-error-400"),
    path('page-error-403/',dashboard_views.page_error_403,name="page-error-403"),
    path('page-error-404/',dashboard_views.page_error_404,name="page-error-404"),
    path('page-error-500/',dashboard_views.page_error_500,name="page-error-500"),
    path('page-error-503/',dashboard_views.page_error_503,name="page-error-503"),
    path('empty-page/',dashboard_views.empty_page,name="empty-page"),


    path('', users_views.password_change, name='password_change'),






    # This Route for PasswordChange
    path('password/', users_views.password_change, name='password_change'),

    # These Routes for PasswordReset
    path('password_reset/', auth_views.PasswordResetView.as_view(
        form_class=EmailValidationOnForgotPassword,
        success_url=reverse_lazy('dashboard:password_reset_done')),name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('dashboard:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

dashboard/cms/blog/forms.py
from django import forms
from dashboard.cms.blog.models import Categories, Blogs, Tags, Metas, Seo
from mptt.forms import TreeNodeMultipleChoiceField,TreeNodeChoiceField


class BlogForm(forms.ModelForm):
    # title = forms.CharField(widget=forms.TextInput(attrs={'name':'blog_title1'}))

    class Meta:
        model = Blogs
        fields = (  
                    'title',
                    'slug',
                    'content',
                    'excerpt',
                    'comment',
                    'password',
                    'status',
                    'visibility',
                    'publish_on',
                    'feature_image',
                    'video_url',
                    'user'
                 )
        widgets = {
        'feature_image': forms.FileInput(),
        }

class MetaForm(forms.ModelForm):
    class Meta:
        model = Metas
        fields = (
                  'title',
                  'value',
                )
class SeoForm(forms.ModelForm):
    class Meta:
        model = Seo
        fields = (
            'title',
            'meta_keywords',
            'meta_descriptions',
            
        )
class TagForm(forms.ModelForm):
    class Meta:
        model = Tags
        fields = (
            'name',           
        )

class CategoriesForm(forms.ModelForm):

    parent = TreeNodeChoiceField(queryset=Categories.objects.all(), level_indicator='+--',required=False)
        
    class Meta:
        model = Categories
        fields = ('title','parent')
        

    

dashboard/cms/contactus/forms.py
from django import forms
from dashboard.cms.contactus.models import ContactUs


class ContactusForm(forms.ModelForm):
    
    class Meta:
        model = ContactUs
        fields = ( 
                  'name',
                  'email',
                  'phone',
                  'message',
                  )

dashboard/cms/contactus/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from dashboard.cms.contactus.models import ContactUs
from dashboard.cms.contactus.forms import ContactusForm
from django.core.paginator import Paginator
from dashboard.cms import utils
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required, permission_required 



@login_required(login_url='dashboard:login')
@permission_required({'contactus.view_contactus'}, raise_exception=True)
def view_contact_us(request):
    id = request.GET.get('id')
    html_data = None
    if id:
        contact_obj = ContactUs.objects.get(id=id)
        html_data=f'''
            <h4>{contact_obj.name}<h4>
            <h4>{contact_obj.email}<h4>
            <h4>{contact_obj.phone}<h4>
            <h4>{contact_obj.message}<h4>
        '''
        response = JsonResponse({"data": html_data})
        response.status_code = 200
    else:
        response = JsonResponse({"data": html_data})
        response.status_code = 200
        
    return response
        

@login_required(login_url='dashboard:login')
@permission_required({'contactus.view_contactus'}, raise_exception=True)
def contact_us(request):
    template_name = "contact-us/contact-us.html"
    add_edit_view = False
    contact_form = ContactusForm()
    contact_list = ContactUs.objects.all()
    filter_form_data=None
    if request.method == "POST":
        filter_name = request.POST.get('filter-contactus-name')
        filter_email = request.POST.get('filter-contactus-email')
        filter_phone = request.POST.get('filter-contactus-phone')
        
        if filter_name or filter_email or filter_phone:
            contact_form = ContactusForm()
            filter_form_data = {
                "filter_name":filter_name,
                "filter_email":filter_email,
                "filter_phone":filter_phone
            }
            contact_list = utils.data_filter_other(filter_form_data,ContactUs)
            if filter_form_data:
                request.session['contactus_filter_data']=filter_form_data   
        else:
            name = request.POST.get('name')
            email = request.POST.get('email')
            phone = request.POST.get('phone')
            if name or email or phone:
                contact_form = ContactusForm(request.POST)
                if contact_form.is_valid():
                    contact_form.save()
                    contact_list = ContactUs.objects.all()
                    messages.success(request,"Contact Add Successfully")
                else:
                    messages.warning(request, contact_form.errors)
    else:
        if 'contactus_filter_data' in list(request.session.keys()) and 'page' in list(request.GET.keys()):
            session_data = request.session.get('contactus_filter_data')
            contact_list = utils.data_filter_other(session_data,ContactUs)
            filter_form_data=request.session.get('contactus_filter_data')
        else:
            if 'contactus_filter_data' in list(request.session.keys()):
                del request.session['contactus_filter_data']
            
    if contact_list:
        paginator = Paginator(contact_list, utils.nodes_per_page()) 
        contact_list=paginator.get_page(request.GET.get('page'))


    if request.user.has_perm('contactus.add_contactus'):
        add_edit_view=True

    context={
        "page_title":"Contact Us",
        "contact_list":contact_list,
        "form_data":filter_form_data,
        "contact_form":contact_form,
        "add_edit_view":add_edit_view,
        "edit":False
    }
    return render(request, template_name,context)


@login_required(login_url='dashboard:login')
@permission_required({'contactus.view_contactus','contactus.change_contactus'}, raise_exception=True)
def edit_contact_us(request,id):
    template_name = "contact-us/contact-us.html"
    add_edit_view = False
    contact_us_obj = get_object_or_404(ContactUs,id=id)

    if request.method == "POST":
        contact_form = ContactusForm(request.POST,instance=contact_us_obj)
       
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request,"Contact Update Successfully")
            return redirect("dashboard:contactus:contact-us")
        else:
            messages.warning(request, contact_form.errors)
    
    else:
        contact_form = ContactusForm(instance=contact_us_obj)
        

    contact_list = ContactUs.objects.all()
    if contact_list:
        paginator = Paginator(contact_list, utils.nodes_per_page()) 
        contact_list=paginator.get_page(request.GET.get('page'))

    if request.user.has_perm('contactus.change_contactus'):
        add_edit_view=True
    context={
        "page_title":"Contact Us",
        "contact_list":contact_list,
        "contact_form":contact_form,
        "add_edit_view":add_edit_view,
        "edit":True
    }
    return render(request, template_name,context)

@login_required(login_url='dashboard:login')
@permission_required({'contactus.view_contactus','contactus.delete_contactus'}, raise_exception=True)
def delete_contact_us(request,id):
    contact_us_obj = ContactUs.objects.get(id=id)
    
    if contact_us_obj:
        contact_us_obj.delete()
        messages.success(request,'Contact Deleted Successfully')
    else:
        messages.warning(request,'Contact Not Valid')
    return redirect("dashboard:contactus:contact-us")
        
    

dashboard/templates/dashboard/sistema/barrios/barrioedit.html
{% extends 'dashboard/elements/layouts/admin.html' %}

{% load static %}

{% block additional_css %}
{% endblock %}

{% block content %}

<!-- modal delete barrio -->
<div class="modal" id="deletebarrio{{barrio.id}}">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center py-5">
                <h4 class="fs-2 my-2">Deleting {{barrio}} permanently...</h4>
                <h4 class="fs-2 my-2">¿Are you sure?</h4>

                <div class="form-floating mt-5">
                    <a href="./" class="btn fs-7 mx-2">
                        <i class="fa-solid fa-arrow-left me-2 fs-7"></i> Nop, go back.
                    </a>
                    <a href="{% url 'dashboard:barriodelete' pk=barrio.id %}" class="shadow-sm btn btn-danger fs-6 p-3">
                        <i class="fa-regular fa-trash-can fs-5 me-1"></i> Yes!
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>



<!-- MAIN -->


        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'dashboard:barrios' %}">Inicio</a></li>

                <li class="breadcrumb-item active"><a href="{% url 'dashboard:barrio' pk=barrio.id %}"> {{barrio}} </a> </li>
            </ol>
        </div>
       
        <div class="row">
            <div class="col-xl-12 col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{{barrio}}</h3>
                        <div class="form-floating pt-4 my-3 d-flex flex-row-reverse">
                                                
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deletebarrio{{barrio.id}}">Delete<span class="btn-icon-end">
                                <i class="fa-solid fa-trash fs-7"></i></span></button>
                        </div>
                                              
                    </div>
                    
                    <div class="card-body">

                        <div class="default-tab">
                            <ul class="nav nav-tabs" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" data-bs-toggle="tab" href="#home"><i class="la la-user me-2"></i> INFORMACIÓN</a>
                                </li>
                                
                                <li class="nav-item">
                                    <a class="nav-link" data-bs-toggle="tab" href="#contact"><i class="las la-comment-dollar me-2"></i>...</a>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="home" role="tabpanel">
                                    <div class="pt-4">
                                        <div class="basic-form">
                                            <form method="post">
                                                {% csrf_token %}
                                                    <div class="pt-1 pb-4">
                                                        <div class="formcontrol">         

                                                            <div class="form-floating mb-3">

                                                                     
                                                                              
                                        
                                                                <div class="form-group my-3">
                                                                    {{editform.nombre}}
                                                                </div>

                                                                <div class="form-group my-3">
                                                                    {{editform.google_account}}
                                                                </div>

                                                                <div class="form-group my-3">
                                                                    {{editform.altitud}}
                                                                </div>
                        
                        
                                                                <div class="form-group my-3">
                                                                    {{editform.latitud}}
                                                                </div>
                        
                        
                                                                <div class="form-group my-3">
                                                                    {{editform.area}}
                                                                </div>
                        

                                                                <div class="form-group my-3">
                                                                    {{editform.descripcion}}
                                                                </div>


                                                                <div class="row form-group my-3">
                                                                    <div class="bootstrap-popover d-inline-block col-9">

                                                                     {{editform.whatsapp_group}}
                                                                    </div>

                                                                    <div class="bootstrap-popover d-inline-block col-3">
                                                                        <button type="button" class="btn btn-primary px-4 " data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right"
                                                                        
                                                                        data-bs-content=
                                                                        "
                                                                          [1]  Ve al Grupo de WhatsApp y toca los puntitos . 

                                                                       . . . [2]  . . . . Ahora en  < Participantes > .  .  . . 

                                                                        . .  . . . . . . . . [3]   Busca el  . . . . . < Enlace de invitación al Grupo > 
                                                                        
                                                                        [4] . . . .  Encuentra el ID al final del link: . . . . . chat.whatsapp.com/'<ID_de_tu_grupo>'  . . " 
                                                                        
                                                                        title="ID del Grupo de WhatsApp ">
                        
                                                                            ¿cómo lo consigo?</button>
                                                                    </div>

                                                                </div>



                                                                           
                                                            </div>
                                                        </div>       
                
                                                        <div class="form-floating pt-4 my-3 d-flex flex-row-reverse">
                                                            <button type="submit" class="shadow-sm btn btn-secondary fs-3 " name="editbarrio"><i class="fa-solid fa-floppy-disk pe-3"></i> Guardar cambios </button>

                                                            <a href="{% url 'dashboard:barrios' %}" class="btn fs-7 mx-2">
                                                                <i class="fa-solid fa-arrow-left me-2 fs-7"></i> Volver
                                                            </a>
                                                        </div>
                
                                                    </div>
                                            </form>
                                            
                
                                           
                
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="tab-pane fade" id="contact">
                                    <div class="pt-4">
                                        
                                    </div>
                                </div>
                            </div>
                        </div>

                       
                    </div>


                    

                    

                    
                </div>
                
            </div>
        </div>







{% endblock %}





{% block additional_js %}


<!-- NEWMODAL -->
<script>
    const deletebarrio = new bootstrap.Modal('#deletebarrio',   {keyboard: true}    )
</script>

{% endblock %}

dashboard/templates/dashboard/sistema/barrios/deletebarrio.html
<!-- Delete Barrio Modal -->
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
               
            <div class="modal-body text-center py-5">
                <h4 class="fs-2 my-2">Deleting {{barrio.nombre}} permanently...</h4>
                <h4 class="fs-2 my-2">¿Are you sure?</h4>

                <div class="form-floating mt-5">
                    <a href="/barrios/" class="btn fs-7 mx-2">
                        <i class="fa-solid fa-arrow-left me-2 fs-7"></i> Nop, go back.
                    </a>
                    <a href="{% url 'dashboard:barriodelete' pk=barrio.id%}" class="shadow-sm btn btn-danger fs-6 p-3">
                        <i class="fa-regular fa-trash-can fs-5 me-1"></i> Yes!
                    </a>
                </div>
            </div>

    </div>
</div>

dashboard/templates/dashboard/sistema/barrios/deletecasa.html
<!-- Delete vivienda Modal -->
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
               
            <div class="modal-body text-center py-5">
                <h4 class="fs-2 my-2">Deleting {{vivienda.get_direccion}}...</h4>
                <h4 class="fs-2 my-2">¿Are you sure?</h4>

                <div class="form-floating mt-5">
                    <a href="/dashboard/barrio/{{vivienda.grupo_barrial.id}}" class="btn fs-7 mx-2">
                        <i class="fa-solid fa-arrow-left me-2 fs-7"></i> Nop, go back.
                    </a>
                    <a href="{% url 'dashboard:viviendadelete' pk=vivienda.id %}" class="shadow-sm btn btn-danger fs-6 p-3">
                        <i class="fa-regular fa-trash-can fs-5 me-1"></i> Yes!
                    </a>
                </div>
            </div>

    </div>
</div>

dashboard/templates/dashboard/sistema/barrios/deleteusuario.html
<!-- Delete vivienda Modal -->
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
               
            <div class="modal-body text-center py-5">
                <h4 class="fs-2 my-2">Deleting {{usuario.get_nombre_completo}}...</h4>
                <h4 class="fs-2 my-2">¿Are you sure?</h4>

                <div class="form-floating mt-5">
                    <a href="{% url 'dashboard:vivienda' pk=usuario.vivienda.id %}" class="btn fs-7 mx-2">
                        <i class="fa-solid fa-arrow-left me-2 fs-7"></i> Nop, go back.
                    </a>
                    <a href="{% url 'dashboard:usuariodelete' pk=usuario.id %}" class="shadow-sm btn btn-danger fs-6 p-3">
                        <i class="fa-regular fa-trash-can fs-5 me-1"></i> Yes!
                    </a>
                </div>
            </div>

    </div>
</div>

dashboard/templates/dashboard/sistema/barrios/deletevivienda.html
<!-- Delete vivienda Modal -->
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
               
            <div class="modal-body text-center py-5">
                <h4 class="fs-2 my-2">Deleting {{vivienda.get_direccion}}...</h4>
                <h4 class="fs-2 my-2">¿Are you sure?</h4>

                <div class="form-floating mt-5">
                    <a href="/dashboard/barrio/{{vivienda.alarma_vecinal.id}}" class="btn fs-7 mx-2">
                        <i class="fa-solid fa-arrow-left me-2 fs-7"></i> Nop, go back.
                    </a>
                    <a href="{% url 'dashboard:viviendadelete' pk=vivienda.id %}" class="shadow-sm btn btn-danger fs-6 p-3">
                        <i class="fa-regular fa-trash-can fs-5 me-1"></i> Yes!
                    </a>
                </div>
            </div>

    </div>
</div>